[package]
name = "neothesia"
version = "0.0.16"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2021"
default-run = "neothesia"

[workspace]
members = [
    "lib-midi",
    "wgpu-jumpstart",
    "neothesia-pipelines",
    "midi-io",
]

[features]
default = ["app"]

app = [
    "rfd",
    "oxi-synth",
    "iced_native",
    "iced_wgpu",
    "iced_graphics",
    "iced_style",
    "play_along",
]
record = ["mpeg_encoder", "build-ffmpeg"]
# Download and compile ffmpeg
build-ffmpeg = ["mpeg_encoder/build"]

play_along = []

synth = []
fluid-synth = ["synth", "cpal", "fluidlite"]
oxi-synth = ["synth", "cpal", "oxisynth"]

[dependencies]
bytemuck = "1.5"
futures = "0.3"

wgpu-jumpstart = { path = "./wgpu-jumpstart" }
neothesia-pipelines = { path = "./neothesia-pipelines" }
midi-io = { path = "./midi-io" }

winit = "0.27"

wgpu = "0.14"
wgpu_glyph = "0.18"


log = "0.4"
env_logger = "0.10"

rfd = { version = "0.10", optional = true }

lib-midi = { path = "./lib-midi" }
midir = "0.8"

fps_ticker = "1.0"

iced_native = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", optional = true }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", features = [
    "png",
    "image",
], optional = true }
iced_graphics = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", optional = true }
iced_style = { git = "https://github.com/iced-rs/iced.git", rev = "da244ff8048e0b339c1502372894a2460a637241", optional = true }

cpal = { version = "0.14", optional = true }
fluidlite = { version = "0.2", features = ["builtin"], optional = true }
oxisynth = { version = "0.0.3", optional = true }

ron = "0.8"
serde = { version = "1.0", features = ["serde_derive"] }

mpeg_encoder = { git = "https://github.com/PolyMeilex/mpeg_encoder_next.git", optional = true }
midi = "0.1"
num = "0.4"
async-thread = "0.1"
# mpeg_encoder = {path="../mpeg_encoder_next", optional=true}

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

[[bin]]
name = "neothesia-cli"
required-features = ["record"]

[[bin]]
name = "neothesia"
required-features = ["app"]
