[package]
name = "wgpu-jumpstart"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = { version = "0.3.61"}
wgpu = { version = "0.15.1", features = ["webgl"] }
log = "0.4"
raw-window-handle = "0.5.0"
console_log = "0.2.1"
bytemuck = "1.13.1"
bytemuck_derive = "1.4.0"
