[package]
name = "neothesia-pipelines"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu-jumpstart = { path = "../wgpu-jumpstart" }
bytemuck = "1.13.1"
bytemuck_derive = "1.4.0"
wasm-bindgen = "0.2.84"
